# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app-starter-aswin"
client_id = "3de71e1b5fb7353295227dc03741eea5"
application_url = "https://sheffield-nhl-brothers-myth.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://sheffield-nhl-brothers-myth.trycloudflare.com/auth/callback",
  "https://sheffield-nhl-brothers-myth.trycloudflare.com/auth/shopify/callback",
  "https://sheffield-nhl-brothers-myth.trycloudflare.com/api/auth/callback",
  "https://sheffield-nhl-brothers-myth.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "storetools-delta.myshopify.com"
